# disease_data.py
# ClinIQ AI — 20 Most Common Diseases Database
# Structured data for patient education and outbreak tracking

DISEASES = [
    {
        "id": "covid19",
        "name": "COVID-19",
        "icon": "",
        "category": "viral",
        "color": "#0891b2",
        "severity": "high",
        "description": "Infectious disease caused by the SARS-CoV-2 coronavirus, affecting the respiratory system.",
        "symptoms": ["Fever or chills", "Dry cough", "Shortness of breath", "Fatigue", "Loss of taste or smell", "Body aches", "Sore throat"],
        "risk_factors": ["Age 60+", "Obesity", "Diabetes", "Heart disease", "Immunocompromised", "Unvaccinated"],
        "prevention": ["Vaccination", "Wear masks in crowds", "Regular handwashing", "Avoid close contact with sick", "Ventilate indoor spaces"],
        "treatment": "Supportive care, antiviral medications (Paxlovid), oxygen therapy for severe cases. Most recover at home.",
        "affected_regions": ["Global — all continents"],
        "incubation": "2–14 days",
        "transmission": "Airborne droplets, close contact",
        "when_to_see_doctor": "Difficulty breathing, persistent chest pain, confusion, bluish lips"
    },
    {
        "id": "influenza",
        "name": "Influenza (Flu)",
        "icon": "",
        "category": "viral",
        "color": "#0891b2",
        "severity": "moderate",
        "description": "Highly contagious viral infection of the respiratory tract occurring seasonally worldwide.",
        "symptoms": ["Sudden high fever", "Severe muscle aches", "Headache", "Dry cough", "Runny nose", "Fatigue", "Chills"],
        "risk_factors": ["Age <5 or >65", "Pregnancy", "Chronic illness", "Weak immune system", "Healthcare workers"],
        "prevention": ["Annual flu vaccine", "Handwashing", "Avoid touching face", "Stay home when sick", "Cover coughs"],
        "treatment": "Rest, fluids, antiviral drugs (oseltamivir/Tamiflu) within 48 hours of symptoms.",
        "affected_regions": ["Northern hemisphere: Oct–Mar", "Southern hemisphere: Apr–Sep", "Tropics: year-round"],
        "incubation": "1–4 days",
        "transmission": "Respiratory droplets, contaminated surfaces",
        "when_to_see_doctor": "Difficulty breathing, persistent vomiting, seizures, severe or worsening symptoms"
    },
    {
        "id": "dengue",
        "name": "Dengue Fever",
        "icon": "",
        "category": "viral",
        "color": "#d97706",
        "severity": "high",
        "description": "Mosquito-borne viral disease causing severe flu-like symptoms; potentially life-threatening in severe form.",
        "symptoms": ["High fever (40°C)", "Severe headache", "Pain behind eyes", "Muscle and joint pain", "Skin rash", "Nausea", "Mild bleeding"],
        "risk_factors": ["Living in tropical areas", "Prior dengue infection", "Young children", "Elderly", "Travel to endemic regions"],
        "prevention": ["Use mosquito repellent", "Wear long sleeves", "Eliminate standing water", "Use mosquito nets", "Dengue vaccine (endemic areas)"],
        "treatment": "No specific antiviral. Supportive care: fluids, rest, paracetamol. Avoid aspirin/ibuprofen.",
        "affected_regions": ["South & Southeast Asia", "Latin America", "Sub-Saharan Africa", "Pacific Islands"],
        "incubation": "4–10 days",
        "transmission": "Aedes mosquito bite",
        "when_to_see_doctor": "Abdominal pain, persistent vomiting, bleeding gums, blood in urine, rapid breathing"
    },
    {
        "id": "malaria",
        "name": "Malaria",
        "icon": "",
        "category": "parasitic",
        "color": "#16a34a",
        "severity": "high",
        "description": "Life-threatening disease caused by Plasmodium parasites transmitted through infected mosquito bites.",
        "symptoms": ["Cyclical fever (every 48–72 hrs)", "Chills and sweating", "Headache", "Nausea and vomiting", "Muscle pain", "Fatigue", "Anaemia"],
        "risk_factors": ["Living/travelling in Africa or Asia", "No chemoprophylaxis", "Young children", "Pregnant women", "No mosquito protection"],
        "prevention": ["Antimalarial medication when travelling", "Insecticide-treated bed nets", "Indoor spraying", "Mosquito repellent", "Protective clothing"],
        "treatment": "Artemisinin-based combination therapy (ACT). Severe malaria requires IV artesunate in hospital.",
        "affected_regions": ["Sub-Saharan Africa (90% of cases)", "South Asia", "Southeast Asia", "Central America"],
        "incubation": "7–30 days",
        "transmission": "Anopheles mosquito bite",
        "when_to_see_doctor": "High fever after travel to endemic area — immediate medical attention required"
    },
    {
        "id": "tuberculosis",
        "name": "Tuberculosis (TB)",
        "icon": "",
        "category": "bacterial",
        "color": "#dc2626",
        "severity": "high",
        "description": "Infectious bacterial disease primarily affecting the lungs, spread through the air.",
        "symptoms": ["Persistent cough (3+ weeks)", "Coughing blood", "Chest pain", "Unintentional weight loss", "Fatigue", "Night sweats", "Fever"],
        "risk_factors": ["HIV infection", "Malnutrition", "Diabetes", "Overcrowded living", "Healthcare workers", "Substance abuse", "Immunosuppression"],
        "prevention": ["BCG vaccine (for infants)", "Early detection and treatment", "Good ventilation", "Cover mouth when coughing", "Complete antibiotic course"],
        "treatment": "6-month course of combination antibiotics (Rifampicin, Isoniazid, Pyrazinamide, Ethambutol). Drug-resistant TB requires longer treatment.",
        "affected_regions": ["India (27% of global cases)", "Southeast Asia", "Africa", "Eastern Europe"],
        "incubation": "Weeks to months (latent TB can reactivate years later)",
        "transmission": "Airborne droplets from active TB patients",
        "when_to_see_doctor": "Cough lasting more than 3 weeks, blood in sputum, unexplained weight loss"
    },
    {
        "id": "pneumonia",
        "name": "Pneumonia",
        "icon": "",
        "category": "mixed",
        "color": "#7c3aed",
        "severity": "high",
        "description": "Infection inflaming air sacs in one or both lungs, caused by bacteria, viruses, or fungi.",
        "symptoms": ["Chest pain when breathing", "Cough with phlegm", "Fever and sweating", "Shortness of breath", "Fatigue", "Nausea", "Confusion (elderly)"],
        "risk_factors": ["Age <2 or >65", "Smoking", "Chronic disease", "Hospitalization", "Weakened immunity", "Recent viral illness"],
        "prevention": ["Pneumococcal vaccine", "Flu vaccine", "Don't smoke", "Handwashing", "Good nutrition"],
        "treatment": "Antibiotics (bacterial), antivirals (viral), antifungals (fungal). Severe cases need hospitalization and oxygen.",
        "affected_regions": ["Global — leading cause of death in children under 5"],
        "incubation": "1–3 days (bacterial), 1–3 weeks (viral)",
        "transmission": "Airborne droplets, aspiration",
        "when_to_see_doctor": "Difficulty breathing, blue lips, confusion, high persistent fever"
    },
    {
        "id": "diabetes_t2",
        "name": "Type 2 Diabetes",
        "icon": "",
        "category": "chronic",
        "color": "#9333ea",
        "severity": "moderate",
        "description": "Chronic condition where the body doesn't use insulin properly, leading to high blood sugar levels.",
        "symptoms": ["Increased thirst", "Frequent urination", "Blurred vision", "Slow-healing sores", "Fatigue", "Unexplained weight loss", "Tingling hands/feet"],
        "risk_factors": ["Obesity", "Physical inactivity", "Age 45+", "Family history", "High blood pressure", "Gestational diabetes history", "PCOS"],
        "prevention": ["Healthy weight", "Regular exercise (150 min/week)", "Balanced diet", "Avoid sugary drinks", "Regular blood sugar screening"],
        "treatment": "Lifestyle changes, metformin, insulin therapy, SGLT2 inhibitors. Regular monitoring of blood glucose.",
        "affected_regions": ["Global epidemic — highest in Middle East, Pacific Islands, USA, India"],
        "incubation": "Develops over years",
        "transmission": "Not contagious — lifestyle and genetic factors",
        "when_to_see_doctor": "Extreme thirst, frequent urination, blurred vision, numbness in feet"
    },
    {
        "id": "hypertension",
        "name": "Hypertension",
        "icon": "️",
        "category": "chronic",
        "color": "#dc2626",
        "severity": "moderate",
        "description": "Persistently elevated blood pressure (≥140/90 mmHg) — the 'silent killer' with often no symptoms.",
        "symptoms": ["Often no symptoms", "Headaches", "Shortness of breath", "Nosebleeds", "Chest pain", "Visual changes", "Dizziness"],
        "risk_factors": ["Age", "Obesity", "Salt-rich diet", "Physical inactivity", "Smoking", "Alcohol", "Stress", "Family history", "Kidney disease"],
        "prevention": ["Reduce salt intake (<5g/day)", "Regular exercise", "Healthy weight", "Limit alcohol", "No smoking", "Manage stress"],
        "treatment": "Lifestyle changes first. Medications: ACE inhibitors, ARBs, calcium channel blockers, diuretics.",
        "affected_regions": ["Global — 1.28 billion adults affected. Highest in Africa and Eastern Europe"],
        "incubation": "Develops gradually over years",
        "transmission": "Not contagious",
        "when_to_see_doctor": "Blood pressure >180/120, severe headache, chest pain, vision problems, difficulty speaking"
    },
    {
        "id": "heart_disease",
        "name": "Coronary Heart Disease",
        "icon": "",
        "category": "chronic",
        "color": "#dc2626",
        "severity": "critical",
        "description": "Narrowing of arteries supplying the heart due to plaque buildup (atherosclerosis).",
        "symptoms": ["Chest pain (angina)", "Shortness of breath", "Heart attack (crushing chest pain)", "Palpitations", "Fatigue", "Dizziness", "Swollen ankles"],
        "risk_factors": ["Hypertension", "High cholesterol", "Smoking", "Diabetes", "Obesity", "Physical inactivity", "Family history", "Age", "Stress"],
        "prevention": ["Heart-healthy diet", "Regular exercise", "No smoking", "Control blood pressure", "Manage cholesterol", "Limit alcohol"],
        "treatment": "Medications (statins, aspirin, beta-blockers), angioplasty/stenting, coronary artery bypass surgery.",
        "affected_regions": ["Global — leading cause of death worldwide. High in Eastern Europe, Central Asia, USA"],
        "incubation": "Decades of progressive arterial damage",
        "transmission": "Not contagious",
        "when_to_see_doctor": "Call emergency: chest pain spreading to arm/jaw, sudden shortness of breath, cold sweats"
    },
    {
        "id": "stroke",
        "name": "Stroke",
        "icon": "",
        "category": "chronic",
        "color": "#7c3aed",
        "severity": "critical",
        "description": "Medical emergency where blood supply to part of the brain is cut off, killing brain cells.",
        "symptoms": ["Sudden face drooping", "Arm weakness", "Speech difficulty", "Severe headache", "Vision loss", "Balance problems", "Confusion"],
        "risk_factors": ["Hypertension", "Atrial fibrillation", "Smoking", "Diabetes", "High cholesterol", "Obesity", "Previous TIA", "Age"],
        "prevention": ["Control blood pressure", "No smoking", "Regular exercise", "Healthy diet", "Limit alcohol", "Manage diabetes", "Anticoagulants if prescribed"],
        "treatment": "Clot-busting drugs (tPA) within 4.5 hours. Thrombectomy for large clots. Rehabilitation therapy.",
        "affected_regions": ["Global — 2nd leading cause of death. High in China, Eastern Europe, Sub-Saharan Africa"],
        "incubation": "Sudden onset — seconds to minutes",
        "transmission": "Not contagious",
        "when_to_see_doctor": "FAST: Face drooping, Arm weakness, Speech difficulty, Time to call emergency NOW"
    },
    {
        "id": "asthma",
        "name": "Asthma",
        "icon": "",
        "category": "chronic",
        "color": "#0891b2",
        "severity": "moderate",
        "description": "Chronic inflammatory lung disease causing narrowed airways, making breathing difficult.",
        "symptoms": ["Wheezing", "Shortness of breath", "Chest tightness", "Coughing (esp. at night)", "Difficulty sleeping", "Symptom triggers (exercise, cold air, allergens)"],
        "risk_factors": ["Family history", "Allergies/eczema", "Obesity", "Smoking exposure", "Air pollution", "Occupational chemicals", "Childhood infections"],
        "prevention": ["Identify and avoid triggers", "Air purifiers", "No smoking indoors", "Keep humidity controlled", "Vaccinations (flu, pneumococcal)"],
        "treatment": "Reliever inhalers (salbutamol), preventer inhalers (corticosteroids), leukotriene antagonists. Have action plan.",
        "affected_regions": ["Global — 262 million affected. High in wealthy countries and urban areas"],
        "incubation": "Often begins in childhood",
        "transmission": "Not contagious",
        "when_to_see_doctor": "Severe shortness of breath, blue lips, reliever inhaler not working — call emergency"
    },
    {
        "id": "copd",
        "name": "COPD",
        "icon": "️",
        "category": "chronic",
        "color": "#d97706",
        "severity": "high",
        "description": "Chronic Obstructive Pulmonary Disease — progressive lung disease blocking airflow, mainly from smoking.",
        "symptoms": ["Persistent cough with mucus", "Shortness of breath (worsens over time)", "Wheezing", "Chest tightness", "Frequent respiratory infections", "Fatigue", "Weight loss (advanced)"],
        "risk_factors": ["Smoking (primary cause, 85%)", "Long-term fume/dust exposure", "Age 40+", "Genetics (Alpha-1 antitrypsin deficiency)", "Air pollution", "Childhood lung infections"],
        "prevention": ["Stop smoking (most important)", "Avoid occupational dust/fumes", "Air pollution reduction", "Flu and pneumococcal vaccines"],
        "treatment": "Bronchodilators, inhaled corticosteroids, pulmonary rehabilitation, oxygen therapy, surgery (severe).",
        "affected_regions": ["Global — 3rd leading cause of death. China, India highest burden"],
        "incubation": "Develops over decades",
        "transmission": "Not contagious",
        "when_to_see_doctor": "Increasing breathlessness, regular exacerbations, cough lasting >3 weeks"
    },
    {
        "id": "cholera",
        "name": "Cholera",
        "icon": "",
        "category": "bacterial",
        "color": "#0891b2",
        "severity": "critical",
        "description": "Acute bacterial diarrheal disease causing severe dehydration, potentially fatal within hours if untreated.",
        "symptoms": ["Sudden watery diarrhoea ('rice-water' stools)", "Vomiting", "Rapid dehydration", "Muscle cramps", "Sunken eyes", "Dry skin", "Rapid heart rate"],
        "risk_factors": ["Contaminated water/food", "Poor sanitation", "Natural disasters/conflict zones", "Living in endemic areas", "Low stomach acid"],
        "prevention": ["Safe drinking water (boil/treat)", "Oral cholera vaccine", "Proper sanitation", "Handwashing with soap", "Avoid raw shellfish in endemic areas"],
        "treatment": "Oral Rehydration Solution (ORS) — 80% of cases. IV fluids for severe dehydration. Antibiotics shorten duration.",
        "affected_regions": ["Sub-Saharan Africa", "South Asia (Bangladesh, India)", "Haiti", "Yemen", "Syria"],
        "incubation": "2 hours – 5 days",
        "transmission": "Contaminated water and food",
        "when_to_see_doctor": "Any suspected cholera — seek immediate care. Can be fatal in hours without treatment"
    },
    {
        "id": "typhoid",
        "name": "Typhoid Fever",
        "icon": "️",
        "category": "bacterial",
        "color": "#dc2626",
        "severity": "high",
        "description": "Systemic bacterial infection caused by Salmonella Typhi through contaminated food and water.",
        "symptoms": ["Sustained high fever (39–40°C)", "Headache", "Weakness and fatigue", "Stomach pain", "Constipation or diarrhoea", "Skin rash ('rose spots')", "Loss of appetite"],
        "risk_factors": ["Travel to endemic countries", "Contaminated water/food", "Poor sanitation", "No vaccination", "Close contact with carrier"],
        "prevention": ["Typhoid vaccine", "Safe water (boiled/bottled)", "Handwashing before eating", "Avoid raw foods in endemic areas", "Proper food handling"],
        "treatment": "Antibiotics (ciprofloxacin, azithromycin). Increasing drug-resistant strains are a concern.",
        "affected_regions": ["South Asia (Pakistan, Bangladesh, India)", "Southeast Asia", "Sub-Saharan Africa", "Latin America"],
        "incubation": "6–30 days",
        "transmission": "Faecal-oral via contaminated food/water",
        "when_to_see_doctor": "Persistent fever >5 days, severe abdominal pain, confusion, rash on abdomen"
    },
    {
        "id": "measles",
        "name": "Measles",
        "icon": "",
        "category": "viral",
        "color": "#dc2626",
        "severity": "high",
        "description": "Highly contagious viral infection preventable by vaccine; can cause serious complications including brain damage.",
        "symptoms": ["High fever", "Cough, runny nose, red eyes", "White spots inside mouth (Koplik's spots)", "Red blotchy skin rash (spreading from face)", "Sensitivity to light", "Fatigue"],
        "risk_factors": ["Unvaccinated", "Infants too young to be vaccinated", "Malnourished children", "Vitamin A deficiency", "Travel to endemic areas", "Immunocompromised"],
        "prevention": ["MMR vaccine — 2 doses (97% effective)", "Vitamin A supplementation", "Isolate infected individuals"],
        "treatment": "No specific antiviral. Supportive care: fluids, Vitamin A, fever management. Antibiotics for secondary infections.",
        "affected_regions": ["Africa", "Southeast Asia", "Eastern Mediterranean", "Europe (recent outbreaks due to low vaccination)"],
        "incubation": "10–14 days",
        "transmission": "Extremely contagious — airborne, one infected person can infect 12–18 others",
        "when_to_see_doctor": "High fever, rash spreading, difficulty breathing, ear pain, confusion"
    },
    {
        "id": "hepatitis_b",
        "name": "Hepatitis B",
        "icon": "",
        "category": "viral",
        "color": "#d97706",
        "severity": "high",
        "description": "Viral liver infection — acute or chronic. Chronic infection can lead to liver cirrhosis and cancer.",
        "symptoms": ["Often asymptomatic (acute)", "Jaundice (yellow skin/eyes)", "Dark urine", "Extreme fatigue", "Nausea/vomiting", "Abdominal pain", "Joint pain"],
        "risk_factors": ["Unprotected sex", "Sharing needles", "Mother to child (birth)", "Healthcare workers", "Unvaccinated", "Blood transfusions in low-income countries"],
        "prevention": ["Hepatitis B vaccine (3 doses)", "Condoms", "Safe needle use", "Screen pregnant mothers", "Blood safety testing"],
        "treatment": "Acute: supportive care. Chronic: antiviral drugs (tenofovir, entecavir) to suppress virus and prevent cirrhosis.",
        "affected_regions": ["Western Pacific (45% of cases)", "Africa", "South Asia. 296 million chronic carriers globally"],
        "incubation": "60–150 days",
        "transmission": "Blood, sexual contact, mother to newborn",
        "when_to_see_doctor": "Yellow skin/eyes, extreme fatigue, dark urine, abdominal swelling"
    },
    {
        "id": "hiv_aids",
        "name": "HIV / AIDS",
        "icon": "",
        "category": "viral",
        "color": "#dc2626",
        "severity": "critical",
        "description": "Human Immunodeficiency Virus destroys immune cells, leading to AIDS if untreated. Lifelong but manageable.",
        "symptoms": ["Early: flu-like (fever, rash, sore throat)", "Latent: often no symptoms", "Advanced AIDS: weight loss, chronic diarrhoea, opportunistic infections, night sweats"],
        "risk_factors": ["Unprotected sex", "Multiple sexual partners", "Sharing needles", "Transfusion with unscreened blood", "Mother to child", "Sexually transmitted infections"],
        "prevention": ["Condoms", "PrEP (pre-exposure prophylaxis)", "Regular testing", "Needle exchange programs", "Antiretroviral therapy (ART) reduces transmission"],
        "treatment": "Antiretroviral therapy (ART) — suppresses virus to undetectable levels. Must be taken lifelong.",
        "affected_regions": ["Sub-Saharan Africa (67% of cases)", "Eastern Europe", "Asia-Pacific", "Caribbean"],
        "incubation": "2–4 weeks for acute infection; years to progress to AIDS untreated",
        "transmission": "Blood, sexual fluids, breast milk",
        "when_to_see_doctor": "Positive HIV test — start ART immediately. Any opportunistic infection"
    },
    {
        "id": "chickenpox",
        "name": "Chickenpox",
        "icon": "",
        "category": "viral",
        "color": "#0891b2",
        "severity": "low",
        "description": "Highly contagious varicella-zoster virus infection causing itchy blisters — usually mild in children.",
        "symptoms": ["Itchy blister-like rash (starting on chest/back/face)", "Fever", "Fatigue", "Headache", "Loss of appetite", "Rash progresses: red spots → blisters → crusts"],
        "risk_factors": ["No vaccination", "No previous infection", "Immunocompromised", "Adults (more severe)", "Newborns", "Pregnant women"],
        "prevention": ["Varicella vaccine — 2 doses (90% effective)", "Avoid contact with infected individuals", "Isolate infected children from school"],
        "treatment": "Antihistamines for itch, paracetamol for fever. Antiviral aciclovir for high-risk patients. Avoid aspirin.",
        "affected_regions": ["Global — highly endemic before vaccination programs. Seasonal peaks in spring"],
        "incubation": "10–21 days",
        "transmission": "Extremely contagious — airborne and direct contact",
        "when_to_see_doctor": "Rash near eyes, bacterial skin infection, high fever, difficulty breathing, confusion"
    },
    {
        "id": "mpox",
        "name": "Mpox (Monkeypox)",
        "icon": "",
        "category": "viral",
        "color": "#d97706",
        "severity": "high",
        "description": "Viral zoonosis (from animals to humans) causing rash and flu-like symptoms; declared WHO PHEIC in 2022 and 2024.",
        "symptoms": ["Painful rash (face, hands, genitals)", "Fever and chills", "Swollen lymph nodes", "Muscle aches", "Backache", "Fatigue", "Lesions that crust over"],
        "risk_factors": ["Close physical/sexual contact with infected person", "Central/West Africa travel", "Men who have sex with men (clade Ib)", "Healthcare workers", "No smallpox vaccination"],
        "prevention": ["JYNNEOS/MVA-BN vaccine", "Avoid close contact with infected", "Condoms (not fully protective)", "Handwashing", "PPE for healthcare workers"],
        "treatment": "Tecovirimat (TPOXX) for severe/high-risk cases. Supportive care for most. Isolate until all lesions crust.",
        "affected_regions": ["DRC and Central Africa (clade Ib — severe)", "Global outbreaks 2022–present (clade IIb)", "Europe, Americas, Asia"],
        "incubation": "3–17 days",
        "transmission": "Close skin-to-skin, respiratory droplets, contaminated objects, animal contact",
        "when_to_see_doctor": "Unexplained rash especially after contact with infected person, fever with lymph node swelling"
    },
    {
        "id": "rotavirus",
        "name": "Rotavirus / Diarrhoeal Disease",
        "icon": "",
        "category": "viral",
        "color": "#16a34a",
        "severity": "moderate",
        "description": "Leading cause of severe diarrhoea in young children worldwide; causes dangerous dehydration.",
        "symptoms": ["Watery diarrhoea", "Vomiting", "Fever", "Abdominal pain", "Dehydration signs", "Loss of appetite", "Lethargy (in children)"],
        "risk_factors": ["Children under 5 (most vulnerable)", "No vaccination", "Contaminated food or water", "Poor hygiene", "Malnutrition", "Crowded settings"],
        "prevention": ["Rotavirus oral vaccine (given at 6 and 10 weeks)", "Breastfeeding", "Handwashing", "Safe water and food preparation", "Proper sanitation"],
        "treatment": "Oral Rehydration Solution (ORS) is first-line. Zinc supplementation. IV fluids for severe dehydration. Rotavirus resolves in 3–8 days.",
        "affected_regions": ["Global — highest mortality in Sub-Saharan Africa and South Asia", "Seasonal peaks in winter months"],
        "incubation": "2 days",
        "transmission": "Faecal-oral route, contaminated surfaces",
        "when_to_see_doctor": "Diarrhoea >3 days in child, blood in stool, signs of dehydration, child unresponsive"
    },
]

# Category metadata
CATEGORIES = {
    "viral":     {"label": "Viral",     "color": "#0891b2", "bg": "#d9f8fd"},
    "bacterial": {"label": "Bacterial", "color": "#dc2626", "bg": "#fee2e2"},
    "parasitic": {"label": "Parasitic", "color": "#16a34a", "bg": "#dcfce7"},
    "chronic":   {"label": "Chronic",   "color": "#7c3aed", "bg": "#ede9fe"},
    "mixed":     {"label": "Mixed",     "color": "#d97706", "bg": "#fef3c7"},
}

# Severity metadata
SEVERITY = {
    "critical": {"label": "Critical", "color": "#dc2626", "bg": "#fee2e2"},
    "high":     {"label": "High",     "color": "#d97706", "bg": "#fef3c7"},
    "moderate": {"label": "Moderate", "color": "#ca8a04", "bg": "#fefce8"},
    "low":      {"label": "Low",      "color": "#16a34a", "bg": "#dcfce7"},
}

def get_all_diseases():
    """Return all diseases with category and severity metadata attached."""
    result = []
    for d in DISEASES:
        d_out = dict(d)
        d_out["category_meta"] = CATEGORIES.get(d["category"], CATEGORIES["viral"])
        d_out["severity_meta"] = SEVERITY.get(d["severity"], SEVERITY["moderate"])
        result.append(d_out)
    return result

def get_disease_by_id(disease_id: str):
    """Return a single disease by its id slug."""
    for d in DISEASES:
        if d["id"] == disease_id:
            d_out = dict(d)
            d_out["category_meta"] = CATEGORIES.get(d["category"], CATEGORIES["viral"])
            d_out["severity_meta"] = SEVERITY.get(d["severity"], SEVERITY["moderate"])
            return d_out
    return None
